### PR TITLE
feat: Add helper methods for creating annotations

### PR DESCRIPTION
**Pull request by SilviaZeta**
## Description
Add some missing methods that help create new annotations.

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

### CODE REVIEW

**Review by cooper667 — APPROVED** [review]

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
Could do with a bit more docstring stuff on what the parameters all mean?

**Review by ChasNelson1990 — APPROVED** [review]
Will there be new tests needed too?

**Comment by SilviaZeta** [comment]
> Will there be new tests needed too?

I wasn't going to add tests for these methods, but could do. Do we want them?

**Comment by ChasNelson1990** [comment]
> > Will there be new tests needed too?
> 
> I wasn't going to add tests for these methods, but could do. Do we want them?

Surely we always want tests ;-)
Maybe we just need an issue in the tests repo right now?

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
